create table if not exists public.scan_feedback (
    id bigint generated by default as identity primary key,
    original_label text not null,
    corrected_label text not null,
    original_category text not null,
    corrected_category text not null check (
        corrected_category in (
            'Organic',
            'Anorganic',
            'Residue',
            'B3 / Hazardous',
            'Reusable'
        )
    ),
    estimated_mass_grams integer not null check (
        estimated_mass_grams between 1 and 100000
    ),
    model_confidence real not null check (
        model_confidence between 0 and 1
    ),
    model_predictions jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.scan_feedback enable row level security;

grant insert on public.scan_feedback to anon, authenticated;
grant usage, select on sequence public.scan_feedback_id_seq to anon, authenticated;

drop policy if exists "Allow scan correction submissions"
    on public.scan_feedback;

create policy "Allow scan correction submissions"
    on public.scan_feedback
    for insert
    to anon, authenticated
    with check (true);